### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by fabiolrodriguez** [RScanavez/WinAuto#2]
.... ▄▄ ▄▄ 
......▄▌▒▒▀▒▒▐▄ 
.... ▐▒▒▒▒▒▒▒▒▒▌
... ▐▒▒▒▒▒▒▒▒▒▒▒▌
....▐▒▒▒▒▒▒▒▒▒▒▒▌
....▐▀▄▄▄▄▄▄▄▄▄▀▌
....▐░░░░░░░░░░░▌
....▐░░░░░░░░░░░▌
....▐░░░░░░░░░░░▌
....▐░░░░░░░░░░░▌
....▐░░░░░░░░░░░▌
....▐░░░░░░░░░░░▌
....▐░░░░░░░░░░░▌
....▐░░░░░░░░░░░▌
....▐░░░░░░░░░░░▌
....▐░░░░░░░░░░░▌
....▐░░░░░░░░░░░▌
...▄█▓░░░░░░░░░▓█▄
..▄▀░░░░░░░░░░░░░ ▀▄
.▐░░░░░░░▀▄▒▄▀░░░░░░▌
▐░░░░░░░▒▒▐▒▒░░░░░░░▌
▐▒░░░░░▒▒▒▐▒▒▒░░░░░▒▌
.▀▄▒▒▒▒▒▄▀▒▀▄▒▒▒▒▒▄▀
.. ▀▀▀▀▀ ▀▀▀▀▀

**Comment by haooliveira84** [comment]
...............…………………………._¸„„„„_ 
…………………….…………...„--~*'¯…….'\ 
………….…………………… („-~~--„¸_….,/ì'Ì 
…….…………………….¸„-^"¯ : : : : :¸-¯"¯/' 
……………………¸„„-^"¯ : : : : : : : '\¸„„,-" 
**¯¯¯'^^~-„„„----~^*'"¯ : : : : : : : : : :¸-" 
.:.:.:.:.„-^" : : : : : : : : : : : : : : : : :„-" 
:.:.:.:.:.:.:.:.:.:.: : : : : : : : : : ¸„-^¯ 
.::.:.:.:.:.:.:.:. : : : : : : : ¸„„-^¯ 
:.' : : '\ : : : : : : : ;¸„„-~" 
:.:.:: :"-„""***/*'ì¸'¯ 
:.': : : : :"-„ : : :"\ 
.:.:.: : : : :" : : : : \, 
:.: : : : : : : : : : : : 'Ì 
: : : : : : :, : : : : : :/ 
"-„_::::_„-*__„„~"

**Comment by haooliveira84** [comment]
…………………...„„-~^^~„-„„_
………………„-^*'' : : „'' : : : : *-„
…………..„-* : : :„„--/ : : : : : : : '\
…………./ : : „-* . .| : : : : : : : : '|
……….../ : „-* . . . | : : : : : : : : |
………...\„-* . . . . .| : : : : : : : :'|
……….../ . . . . . . '| : : : : : : : :|
……..../ . . . . . . . .'\ : : : : : : : |
……../ . . . . . . . . . .\ : : : : : : :|
……./ . . . . . . . . . . . '\ : : : : : /
….../ . . . . . . . . . . . . . *-„„„„-*'
….'/ . . . . . . . . . . . . . . '|
…/ . . . . . . . ./ . . . . . . .| 
../ . . . . . . . .'/ . . . . . . .'|
./ . . . . . . . . / . . . . . . .'|
'/ . . . . . . . . . . . . . . . .'|
'| . . . . . \ . . . . . . . . . .|
'| . . . . . . \„_^- „ . . . . .'|
'| . . . . . . . . .'\ .\ ./ '/ . |
| .\ . . . . . . . . . \ .'' / . '|
| . . . . . . . . . . / .'/ . . .|
| . . . . . . .| . . / ./ ./ . .|

**Comment by fabiolrodriguez** [comment]
…………………...„„-~^^~„-„„_
………………„-^*'' : : „'' : : : : *-„
…………..„-* : : :„„--/ : : : : : : : '\
…………./ : : „-* . .| : : : : : : : : '|
……….../ : „-* . . . | : : : : : : : : |
………...\„-* . . . . .| : : : : : : : :'|
……….../ . . . . . . '| : : : : : : : :|
……..../ . . . . . . . .'\ : : : : : : : |
……../ . . . . . . . . . .\ : : : : : : :|
……./ . . . . . . . . . . . '\ : : : : : /
….../ . . . . . . . . . . . . . *-„„„„-*'
….'/ . . . . . . . . . . . . . . '|
…/ . . . . . . . ./ . . . . . . .| 
../ . . . . . . . .'/ . . . . . . .'|
./ . . . . . . . . / . . . . . . .'|
'/ . . . . . . . . . . . . . . . .'|
'| . . . . . \ . . . . . . . . . .|
'| . . . . . . \„_^- „ . . . . .'|
'| . . . . . . . . .'\ .\ ./ '/ . |
| .\ . . . . . . . . . \ .'' / . '|
| . . . . . . . . . . / .'/ . . .|
| . . . . . . .| . . / ./ ./ . .|

**Comment by fabiolrodriguez** [comment]
───────────────▄▄▄▄▄▄▄─────────── ─────────────▄█░░░█░░░█▄───────── ────────────█░░░░░░░░░░█▌──────── ───────────█░░░░░░░░░░░░█──────── ───────────█░░░░░░░░░░░█▌──────── ──────────██████████████───────── ──────────█░░░░░░░░░░░█▌───────── ─────────█░████░████░░█────────── ─────────█░░░░░░░░░░░░█────────── ─────────█░────░░────░█▌───────── ─────────█░██──░░██──░░█───────── ─────────█░────░░────░░█───────── ────────▄█░░░░░░░░░░░░░██──────── ───────██░░░████████░░░░██─────── ─────██░░░░░░░░░░░░░░░░░░░██───── ───██░░░░░░░░░░░█░░░░░░░░░░▒██─── ─██░░░░░░░░░░░░██░░░░░░░░░░░░░██─ █░░░░░░░░░░░░░██░░░░░░░░░░░░░░░██ █░░░░░░░░░▄▄░██░░░░░░░░░░░░░░░░░█ █▒░░░░░░░█░░▀▄█░░░░░░░░░░░░░░░░░█ ▀██░░░░░░░▀▄░░▀█░░░░░░░░░░░░░░██▀ ──██░░░░░░░░▀▄░░▀░░░░░░░░░░░▒██── ───██████████▀░░░░████████████─── ───█▌▌▌▌▌▌▌▌▀▄▄▀▄▄▀▌▌▌▌▌▌▌▌▌█──── ────▀█▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌▌██▀───── ─────█▌▌▌▌▌▌████████▌▌▌▌▌██────── ──────██▒▒██────────██▒▒██─────── ─── ─­──▀████▀────────▀████▀───────

Share

**Comment by RScanavez** [comment]
kkkkkkkk
